# This is a basic workflow to help you get started with Actions

name: Announcerr-demo

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Announce Product release 
        uses: singhkshitij/announcerr@v1.0.1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Launching my awesomeProduct version ${{ github.event.release.tag_name }}
          body: Just launched new version of my ${{github.repository}} ! It is fully packed with awesome features.
          to: ${{secrets.USER_EMAILS}}
          from: Kshitij Singh # <kshitij@mytrashcode.com>
          content_type: text/html
