# This is a basic workflow to help you get started with Actions

name: Announcerr-demo

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
      - name: Announce Product release 
        uses: singhkshitij/announcerr@v2.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Launching my awesomeProduct version ${{ env.RELEASE_VERSION }}
          body: "file://demo-page.html" #Just launched new version of my ${{github.repository}}
          to: ${{secrets.USER_EMAILS}}
          from: Kshitij Singh # <kshitij@mytrashcode.com>
          content_type: text/html
